- name: Ping an IP from the Windows host
  hosts: "{{ target_hosts }}"
  gather_facts: no

  tasks:
    - name: Ping remote IP
      ansible.windows.win_shell: |
        ping -n 4 172.20.138.13
      register: ping_result

    - name: Show output
      debug:
        var: ping_result.stdout_lines